### PR TITLE
Fix  chunk size calculation

### PR DESCRIPTION
**Pull request by akhillanger**
Tagging @jirikraus for review.

### CODE REVIEW

**Review by jirikraus — CHANGES_REQUESTED** [review]
Please change this consistently for all nvshmem versions.

**Comment by akhillanger** [comment]
@jirikraus Done.

**Comment by akhillanger** [comment]
Can I merge this?

**Comment by jirikraus** [comment]
> @jirikraus Done.

I don't see the change to the non opt nvshmem version. Am I missing that?

**Comment by akhillanger** [comment]
Sorry. Pushed to another remote. Fixed now.

**Review by jirikraus — APPROVED** [review]

**Comment by jirikraus** [comment]
Looks good. Feel free to merge.

**Pull request merged**
